# Generated by Django 5.1.3 on 2024-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True, null=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostepny', models.BooleanField(default=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
